/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TravelCarbonSimulatorImport } from './routes/travel-carbon-simulator'
import { Route as IndexImport } from './routes/index'
import { Route as CCompanyidImport } from './routes/c/$company_id'

// Create/Update Routes

const TravelCarbonSimulatorRoute = TravelCarbonSimulatorImport.update({
  path: '/travel-carbon-simulator',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const CCompanyidRoute = CCompanyidImport.update({
  path: '/c/$company_id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/travel-carbon-simulator': {
      id: '/travel-carbon-simulator'
      path: '/travel-carbon-simulator'
      fullPath: '/travel-carbon-simulator'
      preLoaderRoute: typeof TravelCarbonSimulatorImport
      parentRoute: typeof rootRoute
    }
    '/c/$company_id': {
      id: '/c/$company_id'
      path: '/c/$company_id'
      fullPath: '/c/$company_id'
      preLoaderRoute: typeof CCompanyidImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  TravelCarbonSimulatorRoute,
  CCompanyidRoute,
})

/* prettier-ignore-end */
